elasticsearchHosts: "http://elasticsearch-master:9200"

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: kibana.dev.careerpivot.io
      paths:
        - path: /
  tls:
    - secretName: kibana-tls
      hosts:
        - kibana.dev.careerpivot.io

resources:
  requests:
    cpu: "100m"
    memory: "512Mi"
  limits:
    cpu: "500m"
    memory: "1Gi"
